# Jekyll configuration
excerpt_separator: <!--more-->
theme: minima
plugins:
  - jekyll-feed

# GitHub page configuration
domain: kumojin.github.io
url: https://kumojin.github.io

# Site configuration
title: Kumojin
description: Blog

# minima configuration
show_excerpts: true
rss_feed: false
