# Jekyll configuration
excerpt_separator: <!--more-->
theme: minima
plugins:
  - jekyll-feed

# GitHub page configuration
domain: kumojin.github.io
url: https://kumojin.github.io

# Site configuration
title: Kumojin
description: >-
  Dev tips from the Kumojin team.

# minima configuration
github_username:  kumojin
show_excerpts: true
